@baseURL = http://localhost:3000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MDIyOTk2Y2Y4ZGQwMmYwMzFkMmU5YjgiLCJyb2xlIjoiYmFzaWMiLCJpYXQiOjE2MTI5OTgwMjMsImV4cCI6MTYxMzAwMTYyM30._LPG8_UsrOHUCz9w8UASGbK6U-VEPHHfFjqXJHCe-Hw

GET {{baseURL}}
Authorization: {{token}}

### Auth: SignUp
POST {{baseURL}}/auth/signup
Content-Type: application/json

{
    "username": "loviana4",
    "password": "123456"
}

### Auth: SignIn
POST {{baseURL}}/auth/signin
Content-Type: application/json

{
    "username": "basic",
    "password": "123456"
}

### Auth: RefreshToken
POST {{baseURL}}/auth/refresh-token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MDIwMDBmYjdhYWY1OTk0OGZmZTQwZjMiLCJyb2xlIjoxLCJpYXQiOjE2MTI3MTE3ODgsImV4cCI6MTY0NDI2OTM4OH0.CfsFalZEBckq0UALqpKWZhWvfszKkx-n0xH0cDyC538"
}

### User: Get All User
GET {{baseURL}}/user
Authorization: {{token}}

### User: Create User
POST {{baseURL}}/user
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Loviana Mayoreta",
    "username": "mayoreta2",
    "email": "lovianam2@mail.com",
    "password": "123456",
    "role": 1,
    "address": "Jakarta Selatan"
}

### User: Get User by Id
GET {{baseURL}}/user/6022996cf8dd02f031d2e9b8
Authorization: {{token}}

### User: Update User
PATCH {{baseURL}}/user/6022996cf8dd02f031d2e9b8
Content-Type: application/json
Authorization: {{token}}

{
    "username": "basic",
    "password": "123456",
    "role": "basic",
    "address": "Bandung"
}

### User: Delete User
DELETE {{baseURL}}/user/6020011c7aaf59948ffe40f7
Authorization: {{token}}