@baseURL = http://localhost:3000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MDFmYmQ2YzU5ZThjYTQ4NzVhNDRlNWMiLCJyb2xlIjoxLCJpYXQiOjE2MTI2OTgyMDcsImV4cCI6MTYxMjcwMTgwN30.7nZwLKf26H3od0fAjhsbKzKd_UbfHrOUDgto9KbhsAo

GET {{baseURL}}
Authorization: {{token}}

### Auth: SignUp
POST {{baseURL}}/auth/signup
Content-Type: application/json

{
    "email": "loviana3@mail.com",
    "password": "123456",
    "name": "Loviana",
    "role": 1
}

### Auth: SignIn
POST {{baseURL}}/auth/signin
Content-Type: application/json

{
    "email": "loviana@mail.com",
    "password": "123456"
}

### Auth: RefreshToken
POST {{baseURL}}/auth/refresh-token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MDIwMDBmYjdhYWY1OTk0OGZmZTQwZjMiLCJyb2xlIjoxLCJpYXQiOjE2MTI3MTE3ODgsImV4cCI6MTY0NDI2OTM4OH0.CfsFalZEBckq0UALqpKWZhWvfszKkx-n0xH0cDyC538"
}

### Auth: SignOut
DELETE {{baseURL}}/auth/signout