@baseURL=http://localhost:3000

GET {{baseURL}}

### Auth: SignUp
POST {{baseURL}}/auth/signup
Content-Type: application/json

{
    "email": "loviana4@mail.com",
    "password": "123456",
    "name": "Loviana",
    "role": 1
}

### Auth: SignIn
POST {{baseURL}}/auth/signin
Content-Type: application/json

{
    "email": "loviana@mail.com",
    "password": "123456"
}

### Auth: RefreshToken
POST {{baseURL}}/auth/refresh-token

### Auth: SignOut
DELETE {{baseURL}}/auth/signout